package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.25

import (
	"context"

	"github.com/vladimir-kopaliani/tweets/user_service/internal/entities"
)

// RegisterViaEmail is the resolver for the registerViaEmail field.
func (r *mutationResolver) RegisterViaEmail(ctx context.Context, registerViaEmailInput entities.RegisterViaEmailInput) (*entities.User, error) {
	return r.Service.RegisterUser(ctx, &entities.FullUserInfo{
		User: entities.User{
			FirstName: registerViaEmailInput.FirstName,
			LastName:  registerViaEmailInput.LastName,
			Email:     &registerViaEmailInput.Email,
		},
		Password: registerViaEmailInput.Password,
	})
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
