package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.25

import (
	"context"

	"github.com/vladimir-kopaliani/tweets/auth_service/internal/entities"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, loginInput entities.LoginInput) (*entities.SignInResult, error) {
	return r.Service.SignIn(ctx, &loginInput)
}

// RefreshTokens is the resolver for the refreshTokens field.
func (r *mutationResolver) RefreshTokens(ctx context.Context, refreshTokensInput entities.RefreshTokensInput) (*entities.RefreshTokensResult, error) {
	return r.Service.RefreshTokens(ctx, &refreshTokensInput)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
