package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.25

import (
	"context"

	"github.com/vladimir-kopaliani/tweets/tweet_service/internal/entities"
)

// GetTweetByID is the resolver for the getTweetByID field.
func (r *queryResolver) GetTweetByID(ctx context.Context, input entities.GetTweetByIDInput) (*entities.Tweet, error) {
	return r.Service.GetTweetByID(ctx, input.ID)
}

// GetTweetsByUserID is the resolver for the getTweetsByUserID field.
func (r *queryResolver) GetTweetsByUserID(ctx context.Context, input entities.GetTweetsByUserIDInput) ([]*entities.Tweet, error) {
	return r.Service.GetTweetsByUserID(ctx, input.UserID)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
