package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.25

import (
	"context"

	"github.com/vladimir-kopaliani/tweets/tweet_service/internal/entities"
)

// CreatedAt is the resolver for the createdAt field.
func (r *tweetResolver) CreatedAt(ctx context.Context, obj *entities.Tweet) (*entities.DateTime, error) {
	return (*entities.DateTime)(&obj.CreatedAt), nil
}

// Tweet returns TweetResolver implementation.
func (r *Resolver) Tweet() TweetResolver { return &tweetResolver{r} }

type tweetResolver struct{ *Resolver }
